# mkdocs.yml
site_name: Vision Transformers
site_author: Fahim Rustamy
site_description: >-
  Implementation of vision transformer for image classification
# Repository
repo_name: RustamyF/vision-transformer
repo_url: https://github.com/RustamyF/vision-transformer
theme:
  name: "material"
  features:
    - content.code.annotate


plugins:
    - mkdocstrings:

nav:
  - index.md
  - pytorch_implementation.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/frustamy
